"""baseline

Revision ID: 00002efa29ff
Revises: 
Create Date: 2026-08-29 01:15:16.756664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00002efa29ff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timetable_blocks_id'), table_name='timetable_blocks')
    op.drop_table('timetable_blocks')
    op.drop_index(op.f('ix_workload_configurations_id'), table_name='workload_configurations')
    op.drop_table('workload_configurations')
    op.drop_index(op.f('ix_syllabus_course_code'), table_name='syllabus')
    op.drop_table('syllabus')
    op.add_column('faculty', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('faculty', sa.Column('designation', sa.String(), nullable=False))
    op.add_column('faculty', sa.Column('max_theory_hrs', sa.Float(), nullable=True))
    op.add_column('faculty', sa.Column('max_lab_hrs', sa.Float(), nullable=True))
    op.alter_column('faculty', 'id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_faculty_id'), table_name='faculty')
    op.create_foreign_key(None, 'faculty', 'users', ['user_id'], ['id'])
    op.drop_column('faculty', 'department')
    op.add_column('faculty_preferences', sa.Column('preferred_day', sa.String(), nullable=False))
    op.add_column('faculty_preferences', sa.Column('preferred_period', sa.Integer(), nullable=False))
    op.add_column('faculty_preferences', sa.Column('preference_type', sa.Enum('AVOID', 'PREFER', name='preferencetypeenum'), nullable=False))
    op.alter_column('faculty_preferences', 'faculty_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('ix_faculty_preferences_id'), table_name='faculty_preferences')
    op.drop_column('faculty_preferences', 'subject_name')
    op.drop_column('faculty_preferences', 'status')
    op.add_column('rooms', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('rooms', sa.Column('number', sa.String(), nullable=False))
    op.add_column('rooms', sa.Column('is_lab', sa.Boolean(), nullable=True))
    op.drop_index(op.f('ix_rooms_room_number'), table_name='rooms')
    op.create_unique_constraint(None, 'rooms', ['number'])
    op.drop_column('rooms', 'room_number')
    op.drop_column('rooms', 'room_type')
    op.add_column('users', sa.Column('email', sa.String(), nullable=False))
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=False))
    op.add_column('users', sa.Column('department_id', sa.Integer(), nullable=True))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('MASTER_ADMIN', 'DEAN', 'COORDINATOR', 'FACULTY', 'STUDENT', name='roleenum'),
               existing_nullable=False)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'departments', ['department_id'], ['id'])
    op.drop_column('users', 'faculty_id')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(), nullable=False))
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(), nullable=False))
    op.add_column('users', sa.Column('faculty_id', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'faculty', ['faculty_id'], ['id'])
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=1)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('MASTER_ADMIN', 'DEAN', 'COORDINATOR', 'FACULTY', 'STUDENT', name='roleenum'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
    op.drop_column('users', 'department_id')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'email')
    op.add_column('rooms', sa.Column('room_type', sa.VARCHAR(), nullable=False))
    op.add_column('rooms', sa.Column('room_number', sa.VARCHAR(), nullable=False))
    op.drop_constraint(None, 'rooms', type_='unique')
    op.create_index(op.f('ix_rooms_room_number'), 'rooms', ['room_number'], unique=False)
    op.drop_column('rooms', 'is_lab')
    op.drop_column('rooms', 'number')
    op.drop_column('rooms', 'id')
    op.add_column('faculty_preferences', sa.Column('status', sa.VARCHAR(), nullable=True))
    op.add_column('faculty_preferences', sa.Column('subject_name', sa.VARCHAR(), nullable=False))
    op.create_index(op.f('ix_faculty_preferences_id'), 'faculty_preferences', ['id'], unique=False)
    op.alter_column('faculty_preferences', 'faculty_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('faculty_preferences', 'preference_type')
    op.drop_column('faculty_preferences', 'preferred_period')
    op.drop_column('faculty_preferences', 'preferred_day')
    op.add_column('faculty', sa.Column('department', sa.VARCHAR(), nullable=False))
    op.drop_constraint(None, 'faculty', type_='foreignkey')
    op.create_index(op.f('ix_faculty_id'), 'faculty', ['id'], unique=False)
    op.alter_column('faculty', 'id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('faculty', 'max_lab_hrs')
    op.drop_column('faculty', 'max_theory_hrs')
    op.drop_column('faculty', 'designation')
    op.drop_column('faculty', 'user_id')
    op.create_table('syllabus',
    sa.Column('course_code', sa.VARCHAR(), nullable=False),
    sa.Column('course_title', sa.VARCHAR(), nullable=False),
    sa.Column('course_type', sa.VARCHAR(), nullable=False),
    sa.Column('category', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('course_code')
    )
    op.create_index(op.f('ix_syllabus_course_code'), 'syllabus', ['course_code'], unique=False)
    op.create_table('workload_configurations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('faculty_id', sa.VARCHAR(), nullable=True),
    sa.Column('theory_hours', sa.INTEGER(), nullable=True),
    sa.Column('lab_hours', sa.INTEGER(), nullable=True),
    sa.Column('incharge_hours', sa.INTEGER(), nullable=True),
    sa.Column('max_hours_limit', sa.INTEGER(), nullable=True),
    sa.Column('total_calculated_hours', sa.INTEGER(), nullable=True),
    sa.Column('is_overloaded', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('faculty_id')
    )
    op.create_index(op.f('ix_workload_configurations_id'), 'workload_configurations', ['id'], unique=False)
    op.create_table('timetable_blocks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('faculty_id', sa.VARCHAR(), nullable=False),
    sa.Column('section', sa.VARCHAR(), nullable=False),
    sa.Column('subject', sa.VARCHAR(), nullable=False),
    sa.Column('day', sa.INTEGER(), nullable=False),
    sa.Column('period', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timetable_blocks_id'), 'timetable_blocks', ['id'], unique=False)
    # ### end Alembic commands ###
