/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAllocationRouteImport } from './routes/admin.allocation'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminFacultyRouteImport } from './routes/admin.faculty'
import { Route as AdminPreferencesRouteImport } from './routes/admin.preferences'
import { Route as AdminSetupRouteImport } from './routes/admin.setup'
import { Route as AdminTimetablesRouteImport } from './routes/admin.timetables'
import { Route as AdminWorkloadRouteImport } from './routes/admin.workload'
import { Route as DeanIndexRouteImport } from './routes/dean.index'
import { Route as DeanTimetablesRouteImport } from './routes/dean.timetables'
import { Route as FacultyIndexRouteImport } from './routes/faculty.index'
import { Route as FacultyDashboardRouteImport } from './routes/faculty.dashboard'
import { Route as FacultyTimetableRouteImport } from './routes/faculty.timetable'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAllocationRoute = AdminAllocationRouteImport.update({
  id: '/admin/allocation',
  path: '/admin/allocation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFacultyRoute = AdminFacultyRouteImport.update({
  id: '/admin/faculty',
  path: '/admin/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPreferencesRoute = AdminPreferencesRouteImport.update({
  id: '/admin/preferences',
  path: '/admin/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSetupRoute = AdminSetupRouteImport.update({
  id: '/admin/setup',
  path: '/admin/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTimetablesRoute = AdminTimetablesRouteImport.update({
  id: '/admin/timetables',
  path: '/admin/timetables',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWorkloadRoute = AdminWorkloadRouteImport.update({
  id: '/admin/workload',
  path: '/admin/workload',
  getParentRoute: () => rootRouteImport,
} as any)
const DeanIndexRoute = DeanIndexRouteImport.update({
  id: '/dean/',
  path: '/dean/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeanTimetablesRoute = DeanTimetablesRouteImport.update({
  id: '/dean/timetables',
  path: '/dean/timetables',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyIndexRoute = FacultyIndexRouteImport.update({
  id: '/faculty/',
  path: '/faculty/',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyDashboardRoute = FacultyDashboardRouteImport.update({
  id: '/faculty/dashboard',
  path: '/faculty/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyTimetableRoute = FacultyTimetableRouteImport.update({
  id: '/faculty/timetable',
  path: '/faculty/timetable',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/allocation': typeof AdminAllocationRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/faculty': typeof AdminFacultyRoute
  '/admin/preferences': typeof AdminPreferencesRoute
  '/admin/setup': typeof AdminSetupRoute
  '/admin/timetables': typeof AdminTimetablesRoute
  '/admin/workload': typeof AdminWorkloadRoute
  '/dean/timetables': typeof DeanTimetablesRoute
  '/faculty/dashboard': typeof FacultyDashboardRoute
  '/faculty/timetable': typeof FacultyTimetableRoute
  '/admin/': typeof AdminIndexRoute
  '/dean/': typeof DeanIndexRoute
  '/faculty/': typeof FacultyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/allocation': typeof AdminAllocationRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/faculty': typeof AdminFacultyRoute
  '/admin/preferences': typeof AdminPreferencesRoute
  '/admin/setup': typeof AdminSetupRoute
  '/admin/timetables': typeof AdminTimetablesRoute
  '/admin/workload': typeof AdminWorkloadRoute
  '/dean/timetables': typeof DeanTimetablesRoute
  '/faculty/dashboard': typeof FacultyDashboardRoute
  '/faculty/timetable': typeof FacultyTimetableRoute
  '/admin': typeof AdminIndexRoute
  '/dean': typeof DeanIndexRoute
  '/faculty': typeof FacultyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/allocation': typeof AdminAllocationRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/faculty': typeof AdminFacultyRoute
  '/admin/preferences': typeof AdminPreferencesRoute
  '/admin/setup': typeof AdminSetupRoute
  '/admin/timetables': typeof AdminTimetablesRoute
  '/admin/workload': typeof AdminWorkloadRoute
  '/dean/timetables': typeof DeanTimetablesRoute
  '/faculty/dashboard': typeof FacultyDashboardRoute
  '/faculty/timetable': typeof FacultyTimetableRoute
  '/admin/': typeof AdminIndexRoute
  '/dean/': typeof DeanIndexRoute
  '/faculty/': typeof FacultyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/allocation'
    | '/admin/audit'
    | '/admin/faculty'
    | '/admin/preferences'
    | '/admin/setup'
    | '/admin/timetables'
    | '/admin/workload'
    | '/dean/timetables'
    | '/faculty/dashboard'
    | '/faculty/timetable'
    | '/admin/'
    | '/dean/'
    | '/faculty/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/allocation'
    | '/admin/audit'
    | '/admin/faculty'
    | '/admin/preferences'
    | '/admin/setup'
    | '/admin/timetables'
    | '/admin/workload'
    | '/dean/timetables'
    | '/faculty/dashboard'
    | '/faculty/timetable'
    | '/admin'
    | '/dean'
    | '/faculty'
  id:
    | '__root__'
    | '/'
    | '/admin/allocation'
    | '/admin/audit'
    | '/admin/faculty'
    | '/admin/preferences'
    | '/admin/setup'
    | '/admin/timetables'
    | '/admin/workload'
    | '/dean/timetables'
    | '/faculty/dashboard'
    | '/faculty/timetable'
    | '/admin/'
    | '/dean/'
    | '/faculty/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAllocationRoute: typeof AdminAllocationRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminFacultyRoute: typeof AdminFacultyRoute
  AdminPreferencesRoute: typeof AdminPreferencesRoute
  AdminSetupRoute: typeof AdminSetupRoute
  AdminTimetablesRoute: typeof AdminTimetablesRoute
  AdminWorkloadRoute: typeof AdminWorkloadRoute
  DeanTimetablesRoute: typeof DeanTimetablesRoute
  FacultyDashboardRoute: typeof FacultyDashboardRoute
  FacultyTimetableRoute: typeof FacultyTimetableRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DeanIndexRoute: typeof DeanIndexRoute
  FacultyIndexRoute: typeof FacultyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/allocation': {
      id: '/admin/allocation'
      path: '/admin/allocation'
      fullPath: '/admin/allocation'
      preLoaderRoute: typeof AdminAllocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/faculty': {
      id: '/admin/faculty'
      path: '/admin/faculty'
      fullPath: '/admin/faculty'
      preLoaderRoute: typeof AdminFacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/preferences': {
      id: '/admin/preferences'
      path: '/admin/preferences'
      fullPath: '/admin/preferences'
      preLoaderRoute: typeof AdminPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/setup': {
      id: '/admin/setup'
      path: '/admin/setup'
      fullPath: '/admin/setup'
      preLoaderRoute: typeof AdminSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/timetables': {
      id: '/admin/timetables'
      path: '/admin/timetables'
      fullPath: '/admin/timetables'
      preLoaderRoute: typeof AdminTimetablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/workload': {
      id: '/admin/workload'
      path: '/admin/workload'
      fullPath: '/admin/workload'
      preLoaderRoute: typeof AdminWorkloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dean/': {
      id: '/dean/'
      path: '/dean'
      fullPath: '/dean/'
      preLoaderRoute: typeof DeanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dean/timetables': {
      id: '/dean/timetables'
      path: '/dean/timetables'
      fullPath: '/dean/timetables'
      preLoaderRoute: typeof DeanTimetablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/': {
      id: '/faculty/'
      path: '/faculty'
      fullPath: '/faculty/'
      preLoaderRoute: typeof FacultyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/dashboard': {
      id: '/faculty/dashboard'
      path: '/faculty/dashboard'
      fullPath: '/faculty/dashboard'
      preLoaderRoute: typeof FacultyDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/timetable': {
      id: '/faculty/timetable'
      path: '/faculty/timetable'
      fullPath: '/faculty/timetable'
      preLoaderRoute: typeof FacultyTimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAllocationRoute: AdminAllocationRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminFacultyRoute: AdminFacultyRoute,
  AdminPreferencesRoute: AdminPreferencesRoute,
  AdminSetupRoute: AdminSetupRoute,
  AdminTimetablesRoute: AdminTimetablesRoute,
  AdminWorkloadRoute: AdminWorkloadRoute,
  DeanTimetablesRoute: DeanTimetablesRoute,
  FacultyDashboardRoute: FacultyDashboardRoute,
  FacultyTimetableRoute: FacultyTimetableRoute,
  AdminIndexRoute: AdminIndexRoute,
  DeanIndexRoute: DeanIndexRoute,
  FacultyIndexRoute: FacultyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
